### PR TITLE
Refactor Project to Support Net Standard

### PR DESCRIPTION
**Pull request by maldworth**
So don't accept this PR, I'd recommend first creating a develop branch, so then I can make the PR for develop instead of future.

If you take a look at https://ci.appveyor.com/project/maldworth/filecache, you can see the build is working well now. It also produces the artifacts on commits to develop and master branch. I like to follow [GitVersion](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/), which helps automatically with tags (and pre-release tags too). You can setup the appveyor to be on an account of yours (seeing as you are the project maintainor). It's free and you don't really need to do anything other than log in and link it to your github account. In my fork, I put a tag on the current master as 2.0.3, so then when the develop branch builds, it auto increments the Semver minor, and then the alpha# is figured out. 

Here's my git commit message of all the things I changed.

- Cleaned up namespaces
- Added Appveyor.yml for building + artifacting
- Added development dependency of GitVersion which programatically
creates the version based on git commits + tags. It also will put version
information in the assemblies generated
- Added Cake Build for Appveyor
- Removed Example project, the readme + unit tests should be sufficient
- Converted readme to pure Github Flavored Markdown
- Added in some sleeps in unit tests, the build server was occasionally not
acquiring the semaphore lock.

Let me know if you have any questions!

### CODE REVIEW

**Comment by maldworth** [comment]
Great. Now to get the versions working well. If you could tag the current master branch

`git tag -a v2.0.3`  

and enter a message.

I also noticed that it build the artifacts on the Pull Request. I think I need to tweak the appveyor.yml. I'm looking into that right now.

**Comment by maldworth** [comment]
ok appveyor/cake tweaked. Everything looks good

**Comment by acarteas** [comment]
Okay, tag created.

**Comment by maldworth** [comment]
great, so I think you can continue with the PR as normal. and when you decide everything is good. Once it's merged into develop. A build will kick off, giving the version

`2.1.0-alpha0001`

and that build will have two artifacts. You can then manually upload those to your nuget account as pre-release packages and we can just make sure they look good. Once we are happy with them, I think you can just merge Develop into master. Then push master. I think that will then kick off a build (2.1.0) without the -alpha prelease on the end.

Appveyor does offer the ability that you can put in your nuget key for the feed, then with a click of a button it can upload the packages if you want instead.  

Appveyor even has the option to automatically upload if the build is successfull, but I ususally like having the manual human verification of clicking "publish" before the nuget packages are uploaded.

**Comment by acarteas** [comment]
So it looks like none of the actual cache code had to be changed?  That's both surprising and pretty cool.

**Pull request merged**
