### PR TITLE
Fixed cache collision when name has period.

### PR DESCRIPTION
**Pull request by nick-randal**
Removed Path.GetFileNameWithoutExtension() from GetCachePath().

### CODE REVIEW

**Comment by acarteas** [comment]
It looks like you removed just one call to GetFileNameWithoutExtension.  Are you certain that you won't need to alter all the remaining calls?

**Comment by nick-randal** [comment]
Yes you were right I did not fully understand your cache setup. I have gone
back and done a far more extensive refactor to properly support this.

**Comment by acarteas** [comment]
Cool.  I have family in town this week for the holiday and will take a good look at this some time next week.

**Comment by acarteas** [comment]
Sorry for taking so long to getting back to you.  It looks like the Appveyor build fails and VS won't let me run the unit tests locally.  I get the message:

[7/31/2018 7:35:19 AM Informational] ------ Run test started ------
[7/31/2018 7:35:21 AM Warning] No test is available in D:\code\FileCachePR\src\FileCache.Signed\bin\Debug\net40\FileCache.Signed.dll D:\code\FileCachePR\src\FileCache\bin\Debug\net40\FileCache.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[7/31/2018 7:35:22 AM Warning] No test is available in D:\code\FileCachePR\src\FileCache.UnitTests\bin\Debug\net452\FileCache.UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[7/31/2018 7:35:22 AM Informational] ========== Run test finished: 0 run (0:00:03.0496243) ==========

Does this work locally for you?

**Comment by ndrwrbgs** [comment]
@nick-randal ping :)

**Comment by acarteas** [comment]
Closing as this PR is out of date and release/3.0 in Hash mode will likely address this issue.

**Pull request closed without merging**
